name: "Generate and publish to Snapshot Repository"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Minecraft version from the version manifest"
        required: true

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - name: Cache build and application cache
        uses: actions/cache@v2
        with:
          path: |
            ./build
            ./cache
          key: hashed-mojmap
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate and publish mappings
        run: ./gradlew publish -PminecraftVersion="${{ github.event.inputs.version }}" --stacktrace
        env:
          MAVEN_URL: ${{ secrets.SNAPSHOTS_URL }}
          MAVEN_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}